Various improvements to Llama eval scripts (#556)
Towards OPE-313, OPE-140

- Add Llama 70b GCP eval config
- Fix bug in arg names passed to eval script
- Deleted legacy Oumi eval config. According to Kostas, there's no
reason anyone should be using that now, so removing it to not confuse
users.
- Clean up unneeded vars in config, and ensure all configs are
consistent
- Add validation that for models that require sharding for eval, that
the job is not invoked by Accelerate.

Tested Llama 8B/70B SFT/LoRA evals on GCP/Polaris. On 1 Polaris node, we
achieve ~240 it/s for 8B and ~7 it/s for 70B. Note that while tqdm shows
60 it/s for 8B, that is per GPU, as we do DDP for 8B eval. For LoRA
evals, it's ~10-20% slower than the above speeds.

diff --git a/configs/oumi/jobs/polaris/llama70b_eval.yaml b/configs/oumi/jobs/polaris/llama70b_eval.yaml
--- a/configs/oumi/jobs/polaris/llama70b_eval.yaml
+++ b/configs/oumi/jobs/polaris/llama70b_eval.yaml
@@ -1,4 +1,4 @@
-# Config to eval Llama 3.1 70B Instruct.
+# Config to eval Llama 3.1 70B Instruct on Polaris.
 # Example command:
 # oumi-launch -p configs/oumi/jobs/polaris/llama70b_eval.yaml -c preemptable.$ALCF_USER user=$ALCF_USER
 name: llama70b-eval
@@ -10,6 +10,12 @@ resources:
 
 # Upload working directory to /home/$USER/oumi_launcher/llama70b_eval.
 working_dir: .
+
+envs:
+  # NOTE: For SFT, update this to point to your model checkpoint.
+  MODEL_CHECKPOINT_DIR: meta-llama/Meta-Llama-3.1-70B-Instruct
+  # NOTE: For LoRA, update this to point to your LoRA adapter.
+  LORA_ADAPTER_DIR: ""
 
 # `setup` will always be executed before `run`. It's strongly suggested to set any PBS
 # directives in the `setup` section. Additional commands can also be run here after the
@@ -23,22 +29,23 @@ setup: |
   #PBS -e /eagle/community_ai/jobs/logs/
 
 run: |
-  set -e
-
-  # Various setup for running on Polaris.
+  set -e  # Exit if any command failed.
   source ${PBS_O_WORKDIR}/scripts/polaris/polaris_init.sh
 
-  # NOTE: For SFT, update this to point to your model checkpoint.
-  MODEL_CHECKPOINT_DIR="meta-llama/Meta-Llama-3.1-70B-Instruct"
-  # NOTE: For LoRA, update this to point to your LoRA adapter.
-  LORA_ADAPTER_DIR=""
+  if test ${OUMI_NUM_NODES} -ne 1; then
+    echo "LM Harness supports max 1 node. Actual: ${OUMI_NUM_NODES} nodes."
+    exit 1
+  fi
 
-  echo "Starting evaluation for ${EVAL_CHECKPOINT_DIR} ..."
+  echo "Starting evaluation for ${MODEL_CHECKPOINT_DIR} ..."
+  if test -n "$LORA_ADAPTER_DIR"; then
+    echo "Using LoRA adapter: ${LORA_ADAPTER_DIR}"
+  fi
 
   set -x # Enable command tracing.
   python -m oumi.evaluate \
-        -c configs/oumi/llama70b.eval.yaml \
-        "model.model_name=${MODEL_CHECKPOINT_DIR}" \
-        "model.adapter_model=${LORA_ADAPTER_DIR}"
+    -c configs/oumi/llama70b.eval.yaml \
+    "model.model_name=${MODEL_CHECKPOINT_DIR}" \
+    "model.adapter_model=${LORA_ADAPTER_DIR}"
 
-  echo "Polaris job is all done!"
+  echo -e "Finished eval on node:\n$(cat $PBS_NODEFILE)"
diff --git a/configs/oumi/jobs/polaris/llama8b_eval.yaml b/configs/oumi/jobs/polaris/llama8b_eval.yaml
--- a/configs/oumi/jobs/polaris/llama8b_eval.yaml
+++ b/configs/oumi/jobs/polaris/llama8b_eval.yaml
@@ -1,4 +1,4 @@
-# Config to eval Llama 3.1 8B Instruct.
+# Config to eval Llama 3.1 8B Instruct on Polaris.
 # Example command:
 # oumi-launch -p configs/oumi/jobs/polaris/llama8b_eval.yaml -c debug.$ALCF_USER user=$ALCF_USER
 name: llama8b-eval
@@ -10,6 +10,12 @@ resources:
 
 # Upload working directory to /home/$USER/oumi_launcher/llama8b_eval.
 working_dir: .
+
+envs:
+  # NOTE: For SFT, update this to point to your model checkpoint.
+  MODEL_CHECKPOINT_DIR: meta-llama/Meta-Llama-3.1-8B-Instruct
+  # NOTE: For LoRA, update this to point to your LoRA adapter.
+  LORA_ADAPTER_DIR: ""
 
 # `setup` will always be executed before `run`. It's strongly suggested to set any PBS
 # directives in the `setup` section. Additional commands can also be run here after the
@@ -23,45 +29,24 @@ setup: |
   #PBS -e /eagle/community_ai/jobs/logs/
 
 run: |
-  set -e
-
-  # Various setup for running on Polaris.
+  set -e  # Exit if any command failed.
   source ${PBS_O_WORKDIR}/scripts/polaris/polaris_init.sh
 
-  # NOTE: For SFT, update this to point to your model checkpoint.
-  MODEL_CHECKPOINT_DIR="meta-llama/Meta-Llama-3.1-8B-Instruct"
-  # NOTE: For LoRA, update this to point to your LoRA adapter.
-  LORA_ADAPTER_DIR=""
-
   if test ${OUMI_NUM_NODES} -ne 1; then
-    echo "Evaluation can only run on 1 Polaris node. Actual: ${OUMI_NUM_NODES} nodes."
+    echo "LM Harness supports max 1 node. Actual: ${OUMI_NUM_NODES} nodes."
     exit 1
   fi
 
-  EVALUATION_FRAMEWORK="lm_harness" # Valid values: "lm_harness", "oumi"
-
-  echo "Starting evaluation for ${EVAL_CHECKPOINT_DIR} ..."
-
-  set -x # Enable command tracing.
-
-  TOTAL_NUM_GPUS=$((${OUMI_NUM_NODES} * 4))
-
-  if [ "$EVALUATION_FRAMEWORK" == "lm_harness" ]; then
-      accelerate launch \
-        --num_processes=${TOTAL_NUM_GPUS} \
-        --num_machines=${OUMI_NUM_NODES} \
-        -m oumi.evaluate  \
-        -c configs/oumi/llama8b.eval.yaml \
-        "model.adapter_model=${EVAL_CHECKPOINT_DIR}"
-  elif [ "$EVALUATION_FRAMEWORK" == "oumi" ]; then
-      echo "The custom eval framework is deprecated. Use LM_HARNESS instead."
-      python -m oumi.evaluate \
-        -c configs/oumi/llama8b.eval.legacy.yaml \
-        "model.adapter_model=${EVAL_CHECKPOINT_DIR}"
-  else
-      echo "Unknown evaluation framework: ${EVALUATION_FRAMEWORK}"
-      exit 1
+  echo "Starting evaluation for ${MODEL_CHECKPOINT_DIR} ..."
+  if test -n "$LORA_ADAPTER_DIR"; then
+    echo "Using LoRA adapter: ${LORA_ADAPTER_DIR}"
   fi
 
-  echo -e "Finished eval on ${OUMI_NUM_NODES} node(s):\n$(cat $PBS_NODEFILE)"
-  echo "Polaris job is all done!"
+  set -x # Enable command tracing.
+  accelerate launch \
+    -m oumi.evaluate \
+    -c configs/oumi/llama8b.eval.yaml \
+    "model.model_name=${MODEL_CHECKPOINT_DIR}" \
+    "model.adapter_model=${LORA_ADAPTER_DIR}"
+
+  echo -e "Finished eval on node:\n$(cat $PBS_NODEFILE)"
